<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Rahul" ignored="0" name="Forgot_Password Test" tests="10" failures="1" timestamp="2020-06-12T15:35:38 IST" time="183.887" errors="0">
  <testcase name="existing_email_id" time="20.811" classname="megastores.Forgot_Password">
    <skipped/>
  </testcase> <!-- existing_email_id -->
  <testcase name="existing_email_id" time="0.007" classname="megastores.Forgot_Password">
    <skipped/>
  </testcase> <!-- existing_email_id -->
  <testcase name="existing_email_id" time="0.008" classname="megastores.Forgot_Password">
    <skipped/>
  </testcase> <!-- existing_email_id -->
  <testcase name="existing_email_id" time="0.012" classname="megastores.Forgot_Password">
    <failure type="java.lang.AssertionError" message="expected [http://54.147.24.85/megastores/forgot-password] but found [http://54.147.24.85/megastores/]">
      <![CDATA[java.lang.AssertionError: expected [http://54.147.24.85/megastores/forgot-password] but found [http://54.147.24.85/megastores/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at megastores.Forgot_Password.existing_email_id(Forgot_Password.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- existing_email_id -->
  <testcase name="non_existing_email_id" time="19.323" classname="megastores.Forgot_Password"/>
  <testcase name="existing_phone_number" time="32.69" classname="megastores.Forgot_Password"/>
  <testcase name="non_existing_phone_number" time="20.278" classname="megastores.Forgot_Password"/>
  <testcase name="existing_user_name" time="28.657" classname="megastores.Forgot_Password"/>
  <testcase name="non_existing_username" time="18.376" classname="megastores.Forgot_Password"/>
  <testcase name="empty_field" time="16.027" classname="megastores.Forgot_Password"/>
</testsuite> <!-- Forgot_Password Test -->
